# Generated by Django 3.0 on 2020-01-04 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('Status', models.CharField(choices=[('New', 'New'), ('In_Progress', 'In_Progress'), ('Done', 'Done'), ('Invalid', 'Invalid')], default='New', max_length=100)),
                ('user_assigned_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Assigned', to=settings.AUTH_USER_MODEL)),
                ('user_completed_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Complete', to=settings.AUTH_USER_MODEL)),
                ('user_ticket_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
