# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-06 03:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[(b'N', b'New'), (b'P', b'In Progress'), (b'D', b'Done'), (b'I', b'Invalid')], default=b'N', max_length=1)),
                ('user_assigned_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to=settings.AUTH_USER_MODEL)),
                ('user_completed_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complete', to=settings.AUTH_USER_MODEL)),
                ('user_ticket_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
