# Generated by Django 3.0 on 2020-01-10 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buggy', '0002_auto_20200110_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='bug',
            old_name='Posted',
            new_name='posted',
        ),
        migrations.RenameField(
            model_name='bug',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='bug',
            old_name='Title',
            new_name='title',
        ),
    ]
